### ISSUE TITLE
NoClassDefFoundException in getting Logger

### ISSUE THREAD

**Issue by Dmitry-Borodin** [kohesive/keplin#4]
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/kotlin/com/intellij/openapi/diagnostic/Logger
        at uy.kohesive.keplin.kotlin.script.resolver.AnnotationTriggeredScriptDefinition.<clinit>(AnnotationTriggeredScriptDefinition.kt:70)
        at org.jetbrains.kotlin.jupyter.ReplForJupyter.<init>(repl.kt:22)
        at org.jetbrains.kotlin.jupyter.IkotlinKt.kernelServer(ikotlin.kt:64)
        at org.jetbrains.kotlin.jupyter.IkotlinKt.main(ikotlin.kt:43)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more

I"m trying to make Jupyter for Kotlin work, and now stuck to this bug in keplin - Logger probably not in classpath for 1.1.51 Kotlin.
I use keplin 1.0.0-BETA-14

**Comment by Dmitry-Borodin** [comment]
I wrote the test for keplin, and logger is there. But I don't have it at runitme while using it as a library for some reason...
